@echo off
:: Fichier crée et edité par el.s212 le 10/09/2026 et mit à jour le 10/09/2026
powershell "iwr 'https://github.com/els212/W11-PC-Setup/blob/apps/MediaCreationTool.exe?raw=true' -OutFile '%userprofile%\Desktop\MediaCreationTool.exe'"
echo Plug at least an 8GB USB Stick to proceed...
echo You can use these system settings for installation...
echo Make sure to save files of your USB Stick cause this will erase everything...
echo It can take longer depends on your network speed and USB speed too...
start "" /wait "%userprofile%\Desktop\MediaCreationTool"
cls
explorer "%~dp0"
echo Drag "!Disable Automatic Driver Download.reg" and "!Download the PC-Setup Pack" into your USB Stick...
pause
exit