@echo off
:: Fichier crée et edité par el.s212 le 10/09/2026 et mit à jour le 10/09/2026
powershell "Get-AppxPackage -AllUsers Clipchamp.Clipchamp | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.AV1VideoExtension | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.AVCEncoderVideoExtension | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.BingNews | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.BingSearch | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.BingWeather | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.Edge.GameAssist | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.GetHelp | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.HEIFImageExtension | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.HEVCVideoExtension | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.MicrosoftOfficeHub | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.MicrosoftStickyNotes | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.MPEG2VideoExtension | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.OutlookForWindows | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.PowerAutomateDesktop | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.RawImageExtension | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.Todos | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.VP9VideoExtensions2 | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.WebMediaExtensions | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.Windows.DevHome | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.WindowsAlarms | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.WindowsCamera | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.WindowsFeedbackHub | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.WindowsSoundRecorder | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.WindowsTerminal | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.YourPhone | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers Microsoft.ZuneMusic | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers MicrosoftCorporationII.QuickAssist | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers MicrosoftWindows.Client.WebExperience | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers MicrosoftWindows.CrossDevice | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers MSTeams | Remove-AppxPackage -AllUsers"
powershell "Get-AppxPackage -AllUsers RealtekSemiconductorCorp.RealtekAudioControl | Remove-AppxPackage -AllUsers"
cd %windir%\System32
OneDriveSetup -uninstall
exit