@echo off
powershell "iwr 'https://github.com/els212/W11-PC-Setup/blob/apps/MediaCreationTool.exe?raw=true' -OutFile '%temp%\MediaCreationTool.exe'"
echo Plug at least an 8Go USB Stick to proceed...
echo You can use this system settings for installation...
echo Make sure to save files of your USB Stick cause this will erase everythings...
echo It can be longer depends of your network speed and USB speed too...
start "" /wait "%temp%\MediaCreationTool"
exit